language: rust
sudo: required
dist: trusty
rust:
  - 1.0.0
  - beta
  - nightly
services:
  - docker
script:
  - if [[ $TRAVIS_RUST_VERSION = nightly* ]]; then
      sh ci/run-travis.sh;
    else
      cargo build;
    fi
os:
  - linux
  - osx
env:
  matrix:
    - ARCH=x86_64
    - ARCH=i686
  global:
    secure: eIDEoQdTyglcsTD13zSGotAX2HDhRSXIaaTnVZTThqLSrySOc3/6KY3qmOc2Msf7XaBqfFy9QA+alk7OwfePp253eiy1Kced67ffjjFOytEcRT7FlQiYpcYQD6WNHZEj62/bJBO4LTM9sGtWNCTJVEDKW0WM8mUK7qNuC+honPM=
matrix:
  include:
    - os: linux
      env: TARGET=arm-linux-androideabi
      rust: nightly
    - os: linux
      env: TARGET=x86_64-unknown-linux-musl
      rust: nightly
    - os: linux
      env: TARGET=arm-unknown-linux-gnueabihf
      rust: nightly
    - os: linux
      env: TARGET=mips-unknown-linux-gnu
      rust: nightly
    - os: linux
      env: TARGET=aarch64-unknown-linux-gnu
      rust: nightly
    - os: osx
      env: TARGET=i386-apple-ios
      rust: nightly-2015-09-08
    - os: osx
      env: TARGET=x86_64-apple-ios
      rust: nightly-2015-09-08
notifications:
  email:
    on_success: never
branches:
  only:
    - master
